# Generated by Django 5.1.1 on 2024-10-19 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0005_alter_invoiceworkitem_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='pdf_path',
            field=models.FileField(blank=True, null=True, upload_to='OneDrive/Documents/'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='suma_be_pvm',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
    ]
