# Generated by Django 5.1.1 on 2024-10-19 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0006_invoice_pdf_path_invoice_suma_be_pvm'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='pdf_file',
        ),
    ]
