# Generated by Django 5.1.1 on 2024-10-25 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0007_remove_invoice_pdf_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='pdf_path',
            field=models.URLField(blank=True, null=True),
        ),
    ]
