# Generated by Django 5.1.1 on 2024-11-04 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0008_alter_invoice_pdf_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
